[build]
builder = "DOCKERFILE"
dockerfilePath = "railway.Dockerfile"

[deploy]
startCommand = "grafana-server --config=/etc/grafana/grafana.ini --homepath=/usr/share/grafana --packaging=docker"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { GF_SECURITY_ADMIN_PASSWORD = "admin" }
