apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: synthetic_data
    user: grafana
    secureJsonData:
      password: grafana
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
      postgresVersion: 1400
      timescaledb: true
    editable: true

